### PR TITLE
fix: type context

### LINKED ISSUE #115: [Bug]: Type specific contexts not used when `@type` is aliased.
In particular, if I have the context:
```json
{
  "type": "@type",
  "VerifiableCredential": {
    "@id": "https://www.w3.org/2018/credentials#VerifiableCredential",
    "@context": {
      "credentialSubject": {"@id": "https://www.w3.org/2018/credentials#credentialSubject", "@type": "@id"},
    }
  },
}
```

Then the following correctly gets parsed

```json
{
  "@context": /* above context */,
  "@id": "https://some.credential",
  "credentialSubject": { "@id": "https://some.requestor" },
  "@type": [ "VerifiableCredential" ]
 }
```

however when we parse the following it is missing the triple `<https://some.credential> <https://www.w3.org/2018/credentials#credentialSubject> <https://some.requestor> .`

```json
{
  "@context": /* above context */,
  "@id": "https://some.credential",
  "credentialSubject": { "@id": "https://some.requestor" },
  "type": [ "VerifiableCredential" ]
 }
```

I am actively investigating a fix.

### PR DESCRIPTION
**Pull request by jeswr**
Fixes #115 by deferring addition to the `typeJobs` queue until after the `contextJobs` have completed and then unaliasing the keywords.

### CODE REVIEW

File: lib/JsonLdParser.ts [hunk 1]
```diff
@@ -453,12 +453,8 @@ export class JsonLdParser extends Transform implements RDF.Sink<EventEmitter, RD
               jobs = this.contextJobs[depth] = [];
             }
             jobs.push(valueJobCb);
-          } else if (keys[depth] === '@type'
-            || typeof keys[depth] === 'number' && keys[depth - 1] === '@type') { // Also capture @type with array values
```
Comment (rubensworks) [inline lib/JsonLdParser.ts:457]: Could you move these removed comments to the new location around line 510?

**Review by rubensworks — CHANGES_REQUESTED** [review]
Great! Looks like that fixes it.

**Comment by rubensworks** [comment]
Thanks @jeswr! Released as 3.2.1.
